/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package githubaction.practice;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public String testMethod(){
        return "풀리퀘 실험";
    }

    public static void main(String[] args) {
        System.out.println(new App().testMethod());
    }
}
