/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package githubaction.practice;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App classUnderTest = new App();

    @Test void appHasAGreeting() {
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void appTesting(){
        assertNotNull(classUnderTest.testMethod(), "app should pass the test");
    }
}
